### ISSUE TITLE
tracking column offset?

### ISSUE THREAD

**Issue by thautwarm** [ocaml-community/sedlex#105]
Sedlex is intuitive and easy to use, it works smoothly for my project, until the column information is required for more precise error report.  

So far `lexbuf` provides `curr_line`, and tracking  a `curr_column` could be helpful to similar use cases.

**Comment by pmetzger** [comment]
The library already provides all this via the "position" type. To learn more, read https://ocaml.org/api/Lexing.html and https://ocaml-community.github.io/sedlex/sedlex/Sedlexing/index.html

**Comment by thautwarm** [comment]
It works.
