### ISSUE TITLE
Unbound regexp when defined on previous line

### ISSUE THREAD

**Issue by nobrowser** [ocaml-community/sedlex#114]
Source is here:

[Gitlab link](https://gitlab.com/nobrowser/cincoson/-/blob/master/lib/Json5_lexing.ml)

Output:

```
File "lib/Json5_lexing.ml", line 55, characters 65-74:
55 | let scape = [%sedlex.regexp? latin_scape | uni_scape | c_scape | line_cont]
                                                                      ^^^^^^^^^
Error: Sedlex: unbound regexp line_cont
```

**Comment by nobrowser** [comment]
Hmm , looks like I had `sedlex_regexp` on the line purporting to define `line_cont`, so that explains it. But how come the preprocessor didn't complain? Is this also what I can expect using other ppx preprocessors? That would be depressing.

**Comment by smuenzel** [comment]
The link is no longer working, can you paste the broken code?

**Comment by hhugo** [comment]
> But how come the preprocessor didn't complain?

The error was generated by the preprocessor !

ppxlib or the ocaml compiler itself would have complained about the typo at a later stage with something like

```
File "examples/tokenizer.ml", line 3, characters 15-28:
3 | let digit0 = [%sedlex_regexp? '0' .. '9']
                   ^^^^^^^^^^^^^
Error: Uninterpreted extension 'sedlex_regexp'.
```
  
I think this issue can be closed

**Comment by nobrowser** [comment]
ok
