### ISSUE TITLE
lexbuf should handle invalid unicode input the same way regardless of how it is created.

### ISSUE THREAD

**Issue by hhugo** [ocaml-community/sedlex#133]
Precisely, the following should behave the same when facing invalid input.
- Utf8.from_string
- Utf8.from_gen
- Utf8.from_int_array
- from_int_array
- from_gen

In order for this to work, we need to raise `MalFormed` only when all previous uchar have been consumed already.

**Comment by toots** [comment]
Wouldn't https://github.com/ocaml-community/sedlex/pull/131 address this?

**Comment by hhugo** [comment]
Only for the `from_string` part, and I suspect the current implementation has a non-negligible impact.
I'm working on some alternative.
