### ISSUE TITLE
pos_bol and pos_cnum not in bytes

### ISSUE THREAD

**Issue by remexre** [ocaml-community/sedlex#139]
It appears that the positions produced by `lexing_positions` give the `pos_bol` field in Unicode scalar values rather than in bytes; this breaks the ability to compute a substring in O(1) unless an intermediate buffer is kept in UTF-32.

Would it be practical to add a flag on the lexbuf that keeps at least that field (and maybe `pos_cnum`) in bytes?

**Comment by hhugo** [comment]
You should be able to use `Sedlexing.{Utf8,Utf16}.{lexeme,sub_lexeme}` to extract substrings during lexing.

Both `pos_bol` and `pos_cnum` are scalar `based.`

I guess we could try to track bytes positions as well but that would no work with function such as `from_int_array`.

Maybe you can describe your use case a bit more ?

**Comment by remexre** [comment]
I'm storing pairs of positions in syntax tree nodes, and later when semantic errors are detected, I'd like to print errors that include bits of source, e.g.

```
   | 
24 |     Seq(finger_tree::append(lhs.coerce, finger_tree::G0(), rhs.coerce));
   |                             ^~~
```

When source positions are in bytes, this is easy enough to do; e.g. in the case where the span doesn't cross a newline:

```ocaml
with_file_in start.pos_fname (fun ch ->
  seek_in ch start.pos_bol;
  let print_line_some (n : int) : unit =
    let buf = Bytes.create n in
    really_input ch buf 0 n;
    Term.print_bytes buf
  and print_line_rest () : unit = Term.printf "%s\n" (input_line ch) in
  (* ... *)
  print_line_some (start.pos_cnum - start.pos_bol);
  let start_col = Term.get_column () in
  print_line_some (end_.pos_cnum - start.pos_cnum);
  let end_col = Term.get_column () in
  print_line_rest ();
  (* ... *)
  spaces (start_col - Term.get_column ());
  Term.putch '^';
  dotimes (end_col - Term.get_column ())
    (fun () -> Term.putch '~');
  Term.putch '\n';
  (* ... *))
```

This is pretty clean, and importantly doesn't require reading the entire file. (Honestly, this feels like this is the reason why `pos_bol` exists.)

**Comment by toots** [comment]
Actually I believe that this has been happening for a while with liquidsoap as well, we highlight the source code for errors based on those and it is sometimes off.

Given that our interface for returning lexing position follows OCaml's main lexer, I would consider this as a bug in that we are not respecting the interface that we are suppose to implement.

**Comment by hhugo** [comment]
Reading the documentation of `position`, the current implementation looks correct.
The doc mentions numbers of characters, not numbers of bytes.
```
type position = {
  pos_fname : string;
  pos_lnum : int;
  pos_bol : int;
  pos_cnum : int;
}
(** A value of type [position] describes a point in a source file.
   [pos_fname] is the file name; [pos_lnum] is the line number;
   [pos_bol] is the offset of the beginning of the line (number
   of characters between the beginning of the lexbuf and the beginning
   of the line); [pos_cnum] is the offset of the position (number of
   characters between the beginning of the lexbuf and the position).
   The difference between [pos_cnum] and [pos_bol] is the character
   offset within the line (i.e. the column number, assuming each
   character is one column wide).
```

**Comment by hhugo** [comment]
@remexre, in the code spinet above, I think you also need pos_cnum to be in bytes. If this is correct, could you update the title and description of the issue.

**Comment by toots** [comment]
> Reading the documentation of `position`, the current implementation looks correct. The doc mentions numbers of characters, not numbers of bytes.
> 
> ```
> type position = {
>   pos_fname : string;
>   pos_lnum : int;
>   pos_bol : int;
>   pos_cnum : int;
> }
> (** A value of type [position] describes a point in a source file.
>    [pos_fname] is the file name; [pos_lnum] is the line number;
>    [pos_bol] is the offset of the beginning of the line (number
>    of characters between the beginning of the lexbuf and the beginning
>    of the line); [pos_cnum] is the offset of the position (number of
>    characters between the beginning of the lexbuf and the position).
>    The difference between [pos_cnum] and [pos_bol] is the character
>    offset within the line (i.e. the column number, assuming each
>    character is one column wide).
> ```

This is the exact same description as in https://v2.ocaml.org/api/Lexing.html. Characters, in the `Lexing` context, refers to ASCII characters which are exactly one byte.

Furthermore, having the lexing position dependent of the string format creates non-uniform where the application handling the parser's outcome would have to keep track of the parsed data encoding to report positions. This is not practical.

**Comment by hhugo** [comment]
Note that my emacs setup seems to report locations in term of codepoint. I don't think one should simply change the behavior of  lexing_positions. The current behavior seems useful to report locations to users. Maybe we could extend the api with the desired bytes tracking.

**Comment by toots** [comment]
> Note that my emacs setup seems to report locations in term of codepoint. I don't think one should simply change the behavior of lexing_positions. The current behavior seems useful to report locations to users. Maybe we could extend the api with the desired bytes tracking.

Yes, for backward compatibility if would be nice if we could add new functions that are guaranteed to report position in bytes.

**Comment by hhugo** [comment]
> > Note that my emacs setup seems to report locations in term of codepoint. I don't think one should simply change the behavior of lexing_positions. The current behavior seems useful to report locations to users. Maybe we could extend the api with the desired bytes tracking.
> 
> Yes, for backward compatibility if would be nice if we could add new functions that are guaranteed to report position in bytes.

What would you expect to happen in the case of `from_int_array`/`from_uchar_array` ? raising exception if trying to get location in bytes or assume one byte per codepoint ?

**Comment by remexre** [comment]
> @remexre, in the code spinet above, I think you also need pos_cnum to be in bytes. If this is correct, could you update the title and description of the issue.

Oh, that's true; that wouldn't be as performance-affecting to fix though, I would just need to read the whole line into a buffer at once and decode that, so there still wouldn't need to be a "decode the whole file" step.

I'll put a "and maybe pos_cnum" too.
