### ISSUE TITLE
repo management 

### ISSUE THREAD

**Issue by hhugo** [ocaml-community/sedlex#149]
The following branches can be removed:
- revert-89-master
- rep
- use-from-gen
- release

The following branch could be udpated:
- gh-pages (used to serve https://ocaml-community.github.io/sedlex)
The documentation (there is a link in the main Readme) still references the old 2.0 release https://ocaml-community.github.io/sedlex/.

**Comment by toots** [comment]
This is fixed now!

**Comment by toots** [comment]
I think we're ready for a release, I'll push a branch next.
