### ISSUE TITLE
Difference patterns

### ISSUE THREAD

**Issue by whitequark** [ocaml-community/sedlex#20]
It would be very useful, in particular for implementing some of [Unicode TR31 recommendations](http://www.unicode.org/reports/tr31/#Specific_Character_Adjustments), to be able to have difference patterns, e.g. `Diff ('a'..'z', 'q')` would match any English lowercase letter except "q".

ocamllex also has this operator (named `#`).

**Comment by yallop** [comment]
If I'm not mistaken, this has been fixed by the `Sub` operator in a78520c94.

**Comment by hhugo** [comment]
Can someone close this ?
