### ISSUE TITLE
release

### ISSUE THREAD

**Issue by smolkaj** [ocaml-community/sedlex#57]
It would be great to have a new opam release of sedlex so it can be integrated with jbuilder/dune-based projects (see #54). :)

**Comment by ELLIOTTCABLE** [comment]
What's the version on opam missing, out of curiosity?

**Comment by smolkaj** [comment]
The latest version on opam is https://github.com/alainfrisch/sedlex/releases/tag/v1.99.4, which is from July.

**Comment by sufrin** [comment]
opam currently failing to install sedlex for me. Here's the transcript:

516 $ opam install sedlex
The following actions will be performed:
  ∗  install gen    0.5.1                     [required by sedlex]
  ∗  install sedlex 1.99.4
===== ∗  2 =====
Do you want to continue ? [Y/n] Y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
[default] https://opam.ocaml.org/archives/gen.0.5.1+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/sedlex.1.99.4+opam.tar.gz downloaded

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
∗  installed gen.0.5.1
[ERROR] The compilation of sedlex failed at "make all".
Processing  2/2: [sedlex: ocamlfind remove]
#=== ERROR while installing sedlex.1.99.4 =====================================#
# opam-version 1.2.2
# os           darwin
# command      make all
# path         /Users/sufrin/.opam/system/build/sedlex.1.99.4
# compiler     system (4.07.0)
# exit-code    2
# env-file     /Users/sufrin/.opam/system/build/sedlex.1.99.4/sedlex-93115-a7c577.env
# stdout-file  /Users/sufrin/.opam/system/build/sedlex.1.99.4/sedlex-93115-a7c577.out
# stderr-file  /Users/sufrin/.opam/system/build/sedlex.1.99.4/sedlex-93115-a7c577.err
### stdout ###
# (cd src/lib && /Applications/Xcode.app/Contents/Developer/usr/bin/make all doc)
# ocamlfind ocamlc -package gen -w +A-4-9 -safe-string -c sedlexing.mli sedlexing.ml
# ocamlfind ocamlc -package gen -a -o sedlexing.cma sedlexing.cmo
# rm -rf ../../libdoc
# mkdir ../../libdoc
# ocamlfind ocamldoc -package gen -html sedlexing.mli -d ../../libdoc
# (cd src/syntax && /Applications/Xcode.app/Contents/Developer/usr/bin/make all)
# ocamlfind ocamlc -package ppx_tools_versioned.metaquot_405 -package ocaml-migrate-parsetree -linkall -w +A-4-9-42 -annot -a -o sedlex.cma sedlex_cset.mli sedlex_cset.ml unicode63.mli unicode63.ml sedlex.mli sedlex.ml ppx_sedlex.ml
### stderr ###
# findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /usr/local/lib/ocaml, /usr/local/lib/ocaml/compiler-libs
# File "ppx_sedlex.ml", line 11, characters 5-24:
# Error: Unbound module Ast_convenience_405
# make[1]: *** [sedlex.cma] Error 2
# make: *** [all] Error 2



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
The following actions failed
  ∗  install sedlex 1.99.4
The following changes have been performed
  ∗  install gen 0.5.1

The former state can be restored with:
    opam switch import "~/.opam/system/backup/state-20180727192525.export"

**Comment by pmetzger** [comment]
It might be a good idea to clean up the code for some of the recent changes a bit before doing a new release, but I agree one should happen sooner rather than later.

Also, arguably, it might be good to move sedlex to ocaml-community. Not sure what @alainfrisch (or @Drup) thinks of that.

**Comment by alainfrisch** [comment]
> Also, arguably, it might be good to move sedlex to ocaml-community. Not sure what @alainfrisch (or @Drup) thinks of that.

I was actually thinking about it yesterday.  sedlex was created as the first demo of the ppx "technology" and I've never used it.  Since I don't have the time or motivation to maintain it properly, I'd be more than happy to hand its maintenance over to the community.

**Comment by Drup** [comment]
I was thinking the same thing, but I insist we figure out https://github.com/ocaml-community/manifesto/issues/12 first.

**Comment by pmetzger** [comment]
@Drup In the current case, I'm willing to sign on with you as the co-maintainer of sedlex on ocaml-community, so even if we can't solve the problem in the general case, we have the problem solved in the short run.

**Comment by smolkaj** [comment]
This is outdated and solved
