### ISSUE TITLE
Move sedlex to ocaml-community

### ISSUE THREAD

**Issue by pmetzger** [ocaml-community/sedlex#65]
@drup and @alainfrisch, I think you both support this, yes?

**Comment by Drup** [comment]
Yes.

**Comment by pmetzger** [comment]
Okay, so if one of you can initiate it, we can proceed! Instructions are at the bottom of this page:

https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/

**Comment by pmetzger** [comment]
(Once it is done, I'll accept the transfer on the other end. @alainfrisch, if you don't want further involvement, I won't add you to CODEOWNERS after the transfer, otherwise I will do that and make sure you maintain commit access.)

**Comment by alainfrisch** [comment]
GitHub says: "You don’t have the permission to create repositories on ocaml-community"

**Comment by alainfrisch** [comment]
https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/ :

> Users must have repository creation permissions within the receiving organization before they can transfer a repository that they individually own.

**Comment by pmetzger** [comment]
Ah. @Drup has permission to do this. That said, I can make you (@alainfrisch) a member of ocaml-community as well.

**Comment by pmetzger** [comment]
@alainfrisch invitation sent. You should be able to accept the invitation and then transfer the repo.

**Comment by pmetzger** [comment]
I'm going to call this closed as the move has happened.

**Comment by pmetzger** [comment]
I've now set up a `CODEOWNERS` file with the three of us in it, set up continuous integration (via travis), and sent a PR to update the opam package files for the new location.
