### ISSUE TITLE
Build doesn't work on 4.01 and 4.02, deprecate or fix?

### ISSUE THREAD

**Issue by pmetzger** [ocaml-community/sedlex#66]
The OPAM CI system is failing to build sedlex on 4.01 and 4.02. My taste is to push updates to the opam config that says we don't build on those versions, but I'm not sure what the group consensus will be. @Drup, do you have an opinion?

**Comment by Drup** [comment]
OMP is >= 4.02, so we should definitely ditch 4.01. I have no objection to ditch 4.02 as well, it's quite old now.

**Comment by pmetzger** [comment]
Okay, so I'll do a pull request against the OPAM files removing support <= 4.02.

**Comment by pmetzger** [comment]
See: https://github.com/ocaml/opam-repository/pull/12589

**Comment by ELLIOTTCABLE** [comment]
This is unfortunate, as BuckleScript is still a fork of 4.02.3; I'd much rather see 4.02 supported until BuckleScript's endeavour to move to a newer version of the underlying compiler is completed.

Then again, [I'm biased](https://www.npmjs.com/package/bs-sedlex), soooo …

**Comment by pmetzger** [comment]
Feel free to submit patches so future versions can support 4.02, and if they don't harm anything I see no reason they wouldn't be accepted. However, I don't think we are going to fix the older versions of sedlex, only new releases, so the opam packages for the earlier versions should probably stay as is.
