### ISSUE TITLE
Hosted documentation?

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [ocaml-community/sedlex#67]
I swear, I was previously referencing some hosted documentation of the runtime `Sedlexing` module; but I now cannot find that anywhere.

I can build it locally with `odig` or something, but … this should probably exist, somewhere. `(=`

**Comment by pmetzger** [comment]
I agree, although it's a general problem with most OCaml packages.

**Comment by smolkaj** [comment]
I created a `gh-pages` branch that contains the auto-generated documentation. If one would of the administrators could [set up Github pages](https://help.github.com/en/articles/configuring-a-publishing-source-for-github-pages#enabling-github-pages-to-publish-your-site-from-master-or-gh-pages), we can link to it from the README.

**Comment by pmetzger** [comment]
It seems to already be turned on in settings. I remember that there was some way to kick this if it wasn't working, but I can't remember what it is; can you google around a bit and figure it out?

**Comment by Octachron** [comment]
Isn't the issue that the gh-pages branch need a commit from someone with an admin right (like with yojson)?

**Comment by pmetzger** [comment]
That's possible. I suppose I could check out the branch and then do a null commit and push, should I try?

**Comment by smolkaj** [comment]
Sounds good! Another thing to try: [switch the source to `master branch` and then back to `gh-pages` branch](https://help.github.com/en/articles/configuring-a-publishing-source-for-github-pages#enabling-github-pages-to-publish-your-site-from-master-or-gh-pages).

**Comment by Octachron** [comment]
I found the yojson issue: https://github.com/ocaml-community/yojson/issues/72  which was indeed solved by an empty commit.

**Comment by pmetzger** [comment]
I just did an empty commit and push. (I'm not getting a lot of sleep at the moment, so my memory of these things isn't as good as I'd like.) Let me know if it worked. (And if so, close the issue!)

**Comment by smolkaj** [comment]
It works, and PR #72 adds a link to the README
