### ISSUE TITLE
Support for 4.02.3 dropped?

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [ocaml-community/sedlex#69]
I see that between `1.99.2` and `1.99.4`, Sedlex dropped support for OCaml `4.02.3`. Which of the [changes in 4.03](https://ocaml.org/releases/4.03.html) were needed? Is `4.02.3` support something there's a good reason to lose?

I ask because I'm responsible for providing [`bs-sedlex`](https://github.com/ELLIOTTCABLE/bs-sedlex) and [`ppx-sedlex`](https://github.com/ELLIOTTCABLE/ppx-sedlex) on npm, for use in BuckleScript / Reason projects. Thing is. BuckleScript being updated to a newer OCaml is coming … very slowly.

I'd like to maintain explicit support for `4.02.3` and newer, at least until BuckleScript (which is a pretty big userbase!) moves on. Would this be a lot of extra effort upstream? Can I help out? What is there to do, to get `4.02.3` back in the `.opam`?'

(I don't know if it applies across sedlex's support-matrix; but at least on my macOS 10.14 system, it at least *builds* fine on 4.02: `opam install sedlex=1.99.4 ppx_tools=5.0+4.02.0 ocaml-base-compiler=4.02.3 jbuilder=1.0+beta20 --unlock-base --ignore-constraints-on=ocaml`)

**Comment by ELLIOTTCABLE** [comment]
Do we have testing in-place to ensure that it actually *does* work on older versions? I don't want to lie to the dependency-resolution system! 🤣

**Comment by pmetzger** [comment]
There's the CI system. See the travis files in the top level.

**Comment by ELLIOTTCABLE** [comment]
That's odd — the `.opam` file claims `available: [ ocaml-version >= "4.02.3" ]` for `1.99.4`; but [opam thinks](https://github.com/ocaml/opam-repository/blob/master/packages/sedlex/sedlex.1.99.4/opam) it's `"ocaml" {>= "4.03.0"}`. How on earth did those get out of sync …

Oh. Wow. It looks like their bot mistakenly [broke the package.](https://github.com/ocaml/opam-repository/commit/79d725ba3acfad65b087b5a165d4795f48bdecfd). Am I reading this correctly!?

**Comment by pmetzger** [comment]
The fact that it was failing on the global CI was why we removed support.
