### ISSUE TITLE
js_of_ocaml  Invalid_argument("index out of bounds")

### ISSUE THREAD

**Issue by benkonz** [ocaml-community/sedlex#75]
# Expected Behavior
A `.bc.js` file should get created after running `js_of_ocaml foo.bc`

# Actual Behavior
js_of_ocaml throws an `Error: Invalid_argument("index out of bounds")` while compiling

# Version information
- js_of_ocaml: 3.3.0
- sedlex: 2.0
- ocamlc: 4.07.1

# Steps to reproduce
Create a lexer with multiple lexer definitions, example:
```ocaml
let rec token state buf =
    match%sedlex buf with
    | _ ->  _token buf

and _token buf =
    match%sedlex buf with
    | (Star (Star whitespace, Opt comment, newline), Star whitespace, Opt comment), newline -> TOKEN
    | eof -> EOF
    | _ -> raise (LexError (buf.pos, "Unknown character"))
```

Then compile the code into bytecode and run `js_of_ocaml` on the resulting bytecode.

I'm not sure why this is happening, but I was able to prevent the error from happening when I removed a majority of my lexing rules from the match expression

**Comment by hhugo** [comment]
This very much look like an issue with js_of_ocaml, not sedlex.
Can you post this issue on [js_of_ocaml](https://github.com/ocsigen/js_of_ocaml/issues/new) ?

Also, I didn't manage to reproduce this issue. In particular, your reproduction case does not compile out of the box. Can you provide all the context needed to build your example.

**Comment by benkonz** [comment]
Will do, I wasn't sure which repo to post this issue under. I'll also put together a github repo that reproduces the issue.

**Comment by pmetzger** [comment]
I'm guessing this is indeed a `js_of_ocaml` bug. There should be no circumstances in which the compiler should throw an internal error. I'd suggest that this be opened under js_of_ocaml and closed here.

**Comment by benkonz** [comment]
I've created a simple repo that reproduces the error: https://github.com/benkonz/js_of_ocaml_sedlex_bug. I'm closing this issue and opening a new one in js_of_ocaml to continue this discussion.

**Comment by benkonz** [comment]
Let's continue the discussion here: https://github.com/ocsigen/js_of_ocaml/issues/769. Closing this issue.
