### ISSUE TITLE
Ability to pick up pre-downloaded unicode data

### ISSUE THREAD

**Issue by andyli** [ocaml-community/sedlex#87]
Right now the unicode data is downloaded with curl during build. It would be great if the build system can pick up pre-downloaded files in some specific directory. It would greatly ease the Linux packaging effort, since most distros disallow network access during build, but the unicode data files is already available in some packages (e.g. in Debian, there is unicode-data, which provides the [files](https://packages.debian.org/sid/all/unicode-data/filelist) in `/usr/share/unicode`).

**Comment by toots** [comment]
As documented here: https://github.com/ocaml-community/sedlex/tree/master/src/generator, you do not need to download the unicode data for a production build but instead you should invoke `dune` with the `-p` option:
```
% dune build -p sedlex
(...)
 find _build | grep txt
zsh: done       find _build |
zsh: exit 1     grep txt
% dune build
(...)
% find _build | grep txt
_build/default/src/generator/data/DerivedCoreProperties.txt
_build/default/src/generator/data/PropList.txt
_build/default/src/generator/data/DerivedGeneralCategory.txt
```

**Comment by andyli** [comment]
It works. Thanks!
