### ISSUE TITLE
new_line counting different with from_string and from_channel 

### ISSUE THREAD

**Issue by fblanqui** [ocaml-community/sedlex#96]
We currently get some trouble with new_line counting (see https://github.com/Deducteam/lambdapi/issues/549). When reading from a file, the line position is correctly incremented but not when reading from a string. The code for new_line does not increase the line number in case it is equal to 0: https://github.com/Deducteam/lambdapi/issues/549. Why? If it is on purpose, what is the workaround?

**Comment by ejgallego** [comment]
Ignoring when the starting pos is set to 0 is intended by the docs
```ocaml
val set_position: lexbuf -> Lexing.position -> unit
    (** set the initial tracked input position for [lexbuf].
        If set to [Lexing.dummy_pos], Sedlexing will not track position
        information for you. *)
```
However `from_string` [and possibly other parts] are buggy as they don't correctly set the position so the above applies. This seems to be an optimization in the library as not to allocate memory for positions when not needed.

The whole logic is handled a bit ad-hoc I think so I wonder what would be the best fix.
